// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniShopAdmin.Model.Code;

namespace MiniShopAdmin.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220215152736_updateRenewPackageRemark")]
    partial class updateRenewPackageRemark
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MiniShopAdmin.Model.RenewPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Months")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("OperatorName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RenewPackage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2022, 2, 15, 23, 27, 33, 759, DateTimeKind.Local).AddTicks(2017),
                            Image = "https://gw.alipayobjects.com/zos/rmsportal/gLaIAoVWTtLbBWZNYEMg.png",
                            ModifiedTime = new DateTime(2022, 2, 15, 23, 27, 33, 761, DateTimeKind.Local).AddTicks(905),
                            Months = 6,
                            Name = "半年",
                            Price = 299m,
                            Remark = "续费请联系：18276743761（微信同号）"
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2022, 2, 15, 23, 27, 33, 764, DateTimeKind.Local).AddTicks(5981),
                            Image = "https://gw.alipayobjects.com/zos/rmsportal/iXjVmWVHbCJAyqvDxdtx.png",
                            ModifiedTime = new DateTime(2022, 2, 15, 23, 27, 33, 764, DateTimeKind.Local).AddTicks(6006),
                            Months = 12,
                            Name = "一年",
                            Price = 499m,
                            Remark = "续费请联系：18276743761（微信同号）"
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2022, 2, 15, 23, 27, 33, 764, DateTimeKind.Local).AddTicks(7952),
                            Image = "https://gw.alipayobjects.com/zos/rmsportal/iZBVOIhGJiAnhplqjvZW.png",
                            ModifiedTime = new DateTime(2022, 2, 15, 23, 27, 33, 764, DateTimeKind.Local).AddTicks(7955),
                            Months = 24,
                            Name = "两年",
                            Price = 799m,
                            Remark = "续费请联系：18276743761（微信同号）"
                        },
                        new
                        {
                            Id = 4,
                            CreatedTime = new DateTime(2022, 2, 15, 23, 27, 33, 764, DateTimeKind.Local).AddTicks(9755),
                            Image = "https://gw.alipayobjects.com/zos/rmsportal/uMfMFlvUuceEyPpotzlq.png",
                            ModifiedTime = new DateTime(2022, 2, 15, 23, 27, 33, 764, DateTimeKind.Local).AddTicks(9758),
                            Months = 36,
                            Name = "三年",
                            Price = 1099m,
                            Remark = "续费请联系：18276743761（微信同号）"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
