// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniShopAdmin.Model.Code;

namespace MiniShopAdmin.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220125030546_InitMigrations")]
    partial class InitMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MiniShopAdmin.Model.RenewPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("OperatorName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RenewPackage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2022, 1, 25, 11, 5, 42, 990, DateTimeKind.Local).AddTicks(919),
                            ModifiedTime = new DateTime(2022, 1, 25, 11, 5, 42, 994, DateTimeKind.Local).AddTicks(2763),
                            Name = "半年",
                            Price = 299m
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2022, 1, 25, 11, 5, 42, 998, DateTimeKind.Local).AddTicks(5570),
                            ModifiedTime = new DateTime(2022, 1, 25, 11, 5, 42, 998, DateTimeKind.Local).AddTicks(5599),
                            Name = "一年",
                            Price = 499m
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2022, 1, 25, 11, 5, 42, 998, DateTimeKind.Local).AddTicks(8988),
                            ModifiedTime = new DateTime(2022, 1, 25, 11, 5, 42, 998, DateTimeKind.Local).AddTicks(8996),
                            Name = "两年",
                            Price = 799m
                        },
                        new
                        {
                            Id = 4,
                            CreatedTime = new DateTime(2022, 1, 25, 11, 5, 42, 999, DateTimeKind.Local).AddTicks(2828),
                            ModifiedTime = new DateTime(2022, 1, 25, 11, 5, 42, 999, DateTimeKind.Local).AddTicks(2842),
                            Name = "三年",
                            Price = 1099m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
