// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniShopAdmin.Model.Code;

namespace MiniShopAdmin.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220125094100_RenewAddImage")]
    partial class RenewAddImage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MiniShopAdmin.Model.RenewPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("OperatorName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RenewPackage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2022, 1, 25, 17, 40, 57, 697, DateTimeKind.Local).AddTicks(8367),
                            ModifiedTime = new DateTime(2022, 1, 25, 17, 40, 57, 700, DateTimeKind.Local).AddTicks(9891),
                            Name = "半年",
                            Price = 299m
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2022, 1, 25, 17, 40, 57, 705, DateTimeKind.Local).AddTicks(1225),
                            ModifiedTime = new DateTime(2022, 1, 25, 17, 40, 57, 705, DateTimeKind.Local).AddTicks(1258),
                            Name = "一年",
                            Price = 499m
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2022, 1, 25, 17, 40, 57, 709, DateTimeKind.Local).AddTicks(1328),
                            ModifiedTime = new DateTime(2022, 1, 25, 17, 40, 57, 709, DateTimeKind.Local).AddTicks(1364),
                            Name = "两年",
                            Price = 799m
                        },
                        new
                        {
                            Id = 4,
                            CreatedTime = new DateTime(2022, 1, 25, 17, 40, 57, 709, DateTimeKind.Local).AddTicks(9261),
                            ModifiedTime = new DateTime(2022, 1, 25, 17, 40, 57, 709, DateTimeKind.Local).AddTicks(9281),
                            Name = "三年",
                            Price = 1099m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
