#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM registry.cn-hangzhou.aliyuncs.com/newbe36524/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM registry.cn-hangzhou.aliyuncs.com/newbe36524/sdk:3.1-buster AS build
WORKDIR /src
COPY ["MiniShopAdmin.Api/MiniShopAdmin.Api.csproj", "MiniShopAdmin.Api/"]
COPY ["CommonTools.Core/CommonTools.Core.csproj", "CommonTools.Core/"]
COPY ["Logging.Serilog/Logging.Serilog.csproj", "Logging.Serilog/"]
COPY ["Cache.MemoryCache/Cache.MemoryCache.csproj", "Cache.MemoryCache/"]
COPY ["MiniShopAdmin.Dto/MiniShopAdmin.Dto.csproj", "MiniShopAdmin.Dto/"]
# COPY ["MiniShopAdmin.Model/MiniShopAdmin.Model.csproj", "MiniShopAdmin.Model/"]
# COPY ["Orm.Core/Orm.Core.csproj", "Orm.Core/"]
RUN dotnet restore "MiniShopAdmin.Api/MiniShopAdmin.Api.csproj"
COPY . .
WORKDIR "/src/MiniShopAdmin.Api"
RUN dotnet build "MiniShopAdmin.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MiniShopAdmin.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV INITDB=initdb
ENTRYPOINT ["dotnet", "MiniShopAdmin.Api.dll"]