version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile-Mvc
    ports:
      - ${WEB_PORT}:80
    volumes:
      - type: bind
        source: ${WEB_VOLUME_APPSETTINGS_SOURCE}
        target: /app/appsettings.json
      - type: bind
        source: ${WEB_VOLUME_LOGS_SOURCE}
        target: /app/log

