version: '3.8'

services:
  db:
    image: "mysql:8.0.0"
    ports:
      - ${DB_PORT}:3306
    volumes:
      - type: bind
        source: ${DB_VOLUME_SOURCE}
        target: /var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      BIND-ADDRESS: 0.0.0.0

  web:
    build: 
      context: .
      dockerfile: Dockerfile-Api
    ports:
      - ${WEB_PORT}:80
    networks:
      - backend
    volumes:
      - type: bind
        source: ${WEB_VOLUME_APPSETTINGS_SOURCE}
        target: /app/appsettings.json
      - type: bind
        source: ${WEB_VOLUME_LOGS_SOURCE}
        target: /app/log
    environment:
      INITDB: initdb
      CONNECTIONSTRING: server=db;database=MiniShopDB;uid=root;pwd=${DB_PASSWORD};SslMode=None;ConnectionReset=false;connect timeout=3600
    depends_on:
      - db

networks:
  backend:

