version: '3.8'

services:
  db:
    image: "mysql:8.0.0"
    ports:
      - 3307:3306
    volumes:
      - type: bind
        source: D:/dockervolumes/minishopids/db
        target: /var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      BIND-ADDRESS: 0.0.0.0

  dbinit:
    build: 
      context: .
      dockerfile: Dockerfile-Ids1
    networks:
      - backend
    volumes:
      - type: bind
        source: D:/dockervolumes/minishopids/appsettings.json
        target: /app/appsettings.json
    environment:
      INITDB: initdb
      CONNECTIONSTRING: server=db;database=MiniShopIdsDB;uid=root;pwd=123456;SslMode=None;ConnectionReset=false;connect timeout=3600
    depends_on:
      - db      

  web:
    build: 
      context: .
      dockerfile: Dockerfile-Ids1
    ports:
      - 5001:80
    networks:
      - backend
    volumes:
      - type: bind
        source: D:/dockervolumes/minishopids/appsettings.json
        target: /app/appsettings.json
    environment:
      CONNECTIONSTRING: server=db;database=MiniShopIdsDB;uid=root;pwd=123456;SslMode=None;ConnectionReset=false;connect timeout=3600
    depends_on:
      - db

networks:
  backend:

