#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM registry.cn-hangzhou.aliyuncs.com/newbe36524/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM registry.cn-hangzhou.aliyuncs.com/newbe36524/sdk:3.1-buster AS build
WORKDIR /src
COPY ["MiniShop.Mvc/MiniShop.Mvc.csproj", "MiniShop.Mvc/"]
COPY ["CommonTools.Core/CommonTools.Core.csproj", "CommonTools.Core/"]
COPY ["MiniShop.Dto/MiniShop.Dto.csproj", "MiniShop.Dto/"]
COPY ["MiniShopAdmin.Dto/MiniShopAdmin.Dto.csproj", "MiniShopAdmin.Dto/"]
RUN dotnet restore "MiniShop.Mvc/MiniShop.Mvc.csproj"
COPY . .
WORKDIR "/src/MiniShop.Mvc"
RUN dotnet build "MiniShop.Mvc.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MiniShop.Mvc.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MiniShop.Mvc.dll"]